### ISSUE TITLE
volume controls gone in android 12

### ISSUE THREAD

**Issue by DetachHead** [musicbeeremote/mbrc#235]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

the volume slider for musicbee remote doesn't show up anymore

![image](https://user-images.githubusercontent.com/57028336/141603665-e623a199-26e1-482c-a31f-be1ff6e28965.png)

### Steps To Reproduce

1. start playing music through the app
2. press the volume up/down keys

### Environment

```markdown
- App Version: v1.5.1
- Android Version: 12
- Device: pixel 3a
```

**Comment by kelsos** [comment]
Hey @DetachHead unfortunately I can't do anything about this since this is an Android issue. You can find more information about it in the following article.

https://www.androidpolice.com/google-had-to-remove-cast-volume-controls-in-android-12-for-legal-reasons/

According to what I have read it should be added back to Android 12.1.
